using Macad.Common;
using Macad.Core.Geom;
using Macad.Occt;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;

namespace Macad.Core.Shapes;

using ShapeNameDictionary = Dictionary<TopoDS_Shape, (int Index, List<TopoDS_Shape> Sources)>;

//--------------------------------------------------------------------------------------------------

public static class SubshapeReferenceUtils
{
    /// <summary>
    /// Delegate for adding a named subshape. The callback provides the name, shape, index, and sources of the subshape.
    /// </summary>
    public delegate void NamedSubshapeCallback(string name, TopoDS_Shape shape, int index, TopoDS_Shape[] sources);

    //--------------------------------------------------------------------------------------------------

    #region Create names for Primitives

    /// <summary>
    /// Creates subshape names for a given algorithm and invokes the provided callback for each named subshape.
    /// This is typically used to create names for subshapes generated by primitive generation algorithms which
    /// does not have a source shape.
    /// Supports algorithms based on BRepPrim_Wedge and BRepPrim_OneAxis.
    /// </summary>
    /// <param name="algo">The algorithm for which to create subshape names.</param>
    /// <param name="addNamedSubshape">The callback to add named subshapes.</param>
    public static void CreateSubshapeNames<T>(T algo, NamedSubshapeCallback addNamedSubshape) where T : class
    {
        switch (algo)
        {
            case BRepPrim_Wedge wedge:
                _CreateSubshapeNames(wedge, addNamedSubshape);
                return;

            case BRepPrim_OneAxis oneAxis:
                _CreateSubshapeNames(oneAxis, addNamedSubshape);
                return;
        }
    }

    //--------------------------------------------------------------------------------------------------

    static string[] _WedgeFaceNames;
    static string[] _WedgeEdgeNames;

    static void _CreateSubshapeNames(BRepPrim_Wedge wedge, NamedSubshapeCallback addNamedSubshape)
    {
        // Init static fields
        _WedgeFaceNames ??= Enum.GetValues<BRepPrim_Direction>().Select(d1 => string.Intern($"{d1}")).ToArray();
        _WedgeEdgeNames ??= Enum.GetValues<BRepPrim_Direction>().SelectMany(d1 => Enum.GetValues<BRepPrim_Direction>().Select(d2 =>string.Intern($"{d1}{d2}"))).ToArray();

        // Enumerate faces and edges
        foreach (var d1 in Enum.GetValues<BRepPrim_Direction>())
        {
            if (wedge.HasFace(d1))
            {
                addNamedSubshape(_WedgeFaceNames[(int)d1], wedge.Face(d1), 0, null);
            }

            foreach (var d2 in Enum.GetValues<BRepPrim_Direction>())
            {
                // Skip impossible values (e.g. XMin and XMax)
                // Check here to avoid throwing a Standard_DomainError exception in HasEdge()
                if ((int)d1 / 2 == (int)d2 / 2)
                    continue;

                if (wedge.HasEdge(d1, d2))
                {
                    addNamedSubshape(_WedgeEdgeNames[(int)d1*6+(int)d2], wedge.Edge(d1, d2), 0, null);
                }
            }
        }
    }

    //--------------------------------------------------------------------------------------------------

    static void _CreateSubshapeNames(BRepPrim_OneAxis oneAxis, NamedSubshapeCallback addNamedSubshape)
    {
        addNamedSubshape("Lateral", oneAxis.LateralFace(), 0, null);
        if (oneAxis.HasBottom())
        {
            addNamedSubshape("Bottom", oneAxis.BottomFace(), 0, null);
            if (oneAxis.HasSides())
            {
                addNamedSubshape("SideBottom", oneAxis.StartBottomEdge(), 0, null);
                addNamedSubshape("SideBottom", oneAxis.EndBottomEdge(), 1, null);
            }
        }

        var edge = oneAxis.BottomEdge();
        if (edge != null)
        {
            addNamedSubshape("Bottom", edge, 0, null);
        }

        if (oneAxis.HasTop())
        {
            addNamedSubshape("Top", oneAxis.TopFace(), 0, null);
            if (oneAxis.HasSides())
            {
                addNamedSubshape("SideTop", oneAxis.StartTopEdge(), 0, null);
                addNamedSubshape("SideTop", oneAxis.EndTopEdge(), 1, null);
            }
        }

        edge = oneAxis.TopEdge();
        if (edge != null)
        {
            addNamedSubshape("Top", edge, 0, null);
        }

        if (oneAxis.HasSides())
        {
            addNamedSubshape("Axis", oneAxis.AxisEdge(), 0, null);
            addNamedSubshape("Side", oneAxis.StartFace(), 0, null);
            addNamedSubshape("Side", oneAxis.StartEdge(), 0, null);
            addNamedSubshape("Side", oneAxis.EndFace(), 1, null);
            addNamedSubshape("Side", oneAxis.EndEdge(), 1, null);
        }
        else
        {
            var seamEdge = oneAxis.LateralWire().Edges().FirstOrDefault(e => !BRep_Tool.IsClosed(e));
            if (seamEdge != null)
            {
                addNamedSubshape("Seam", seamEdge, 0, null);
            }
        }
    }

    //--------------------------------------------------------------------------------------------------

    #endregion

    #region Create names for Modifiers

    public struct CreateModifierSubshapeContext
    {
        public ModificationInfo CurrentModification;
        public ShapeNameDictionary ShapeDictionary;
    }

    //--------------------------------------------------------------------------------------------------

    public delegate void SubshapeModificationFilter(CreateModifierSubshapeContext context);

    //--------------------------------------------------------------------------------------------------

    /// <summary>
    /// Holds information about a modification. At minimum, it contains a bit value and a history.
    /// The instance can be created from several sources, including BRepTools_History, BRepAlgoAPI_BuilderAlgo, and BRepBuilderAPI_Transform,
    /// which will automatically extract all useful information.
    /// </summary>
    public class ModificationInfo
    {
        public int Index { get; set; }
        public BRepTools_History History { get; set; }
        public TopoDS_Shape ResultShape { get; set; }
        public List<TopoDS_Edge> AuxEdges { get; set; }
        public SubshapeModificationFilter[] Filters { get; set; }

        //--------------------------------------------------------------------------------------------------

        public ModificationInfo(int index, BRepTools_History history)
        {
            Index = index;
            History = history;
        }

        //--------------------------------------------------------------------------------------------------

        public ModificationInfo(int index, BRepAlgoAPI_BuilderAlgo builderAlgo)
        {
            Index = index;
            History = builderAlgo.History();
            ResultShape = builderAlgo.Shape();
            AuxEdges = builderAlgo.SectionEdges().Select(e => e.ToEdge())
                                                   .Where(e => e != null && EdgeAlgo.IsEdgeInShape(e, ResultShape))
                                                   .ToList();
            Filters = [_UniquifyByAdjacentFaces, _UniquifyByAdjacentSplitEdgeFaces, _RemoveBijective];
        }

        //--------------------------------------------------------------------------------------------------

    }

    //--------------------------------------------------------------------------------------------------

    /// <summary>
    /// Creates subshape names for a given source shape based on the provided histories.
    /// Each history is associated with a specific bit value, which is used to create a unique index
    /// for the modified shapes.
    /// The histories list can contain various classes which contain history information. The following are currently supported:
    /// BRepTools_History, BRepAlgoAPI_BuilderAlgo, BRepBuilderAPI_Transform.
    /// </summary>
    /// <param name="name">The name for the subshapes.</param>
    /// <param name="sourceShapes">The source shapes.</param>
    /// <param name="modifications">Modification histories with an integer index; if multiple modifications are provided, each index must be a distinct single-bit value.</param>
    /// <param name="addNamedSubshape">The callback to add named subshapes.</param>
    public static void CreateSubshapeNames(string name, IEnumerable<TopoDS_Shape> sourceShapes, IList<ModificationInfo> modifications, NamedSubshapeCallback addNamedSubshape)
    {
        if (modifications.Count > 1)
        {
            // Validate Bit values: no duplicates, all single bit
            Debug.Assert(modifications.All(mod => int.PopCount(mod.Index) == 1), "Multiple modifications must have single bit values.");
            Debug.Assert(!modifications.GroupBy(mod => mod.Index).Any(g => g.Count() > 1), "Duplicate Bit values found in histories list.");
        }

        // Process shapes
        Dictionary<TopoDS_Shape, (int Index, List<TopoDS_Shape> Sources)> modifiedShapeDict = new();
        List<TopoDS_Shape> inputShapes = new();
        foreach (var shape in sourceShapes)
        {
            inputShapes.AddRange(shape.Faces());
            inputShapes.AddRange(shape.Edges());
        }

        // This holds all the shapes which were in the original shape list
        List<TopoDS_Shape> inputShapeList = new(inputShapes);
        // This is a working copy of the input shape list, which will be enhanced as we process the histories
        List<TopoDS_Shape> currentShapeList = new(inputShapeList);

        foreach (var modification in modifications)
        {
            int currentShapeCount = currentShapeList.Count;
            for (var i = 0; i < currentShapeCount; i++)
            {
                var currentShape = currentShapeList[i];
                List<TopoDS_Shape> modifiedShapes = _GetModifiedShapes(currentShape, modification.History);

                foreach (var modifiedShape in modifiedShapes)
                {
                    // Otherwise we would end up with a shape referencing itself, which leads to infinite loops
                    if (currentShape.IsSame(modifiedShape))
                        continue;
                    var modifiedShapeKey = modifiedShapeDict.Keys.FirstSameOrDefault(modifiedShape);

                    // If the source is not from input shapes list, that means it comes from a prior algo. 
                    if (!inputShapeList.ContainsSame(currentShape))
                    {
                        var currentShapeKey = modifiedShapeDict.Keys.FirstSameOrDefault(currentShape);
                        if (currentShapeKey != null)
                        {
                            // If the shape comes from a prior algo, reference it. If not, replace it.
                            var currentShapeValue = modifiedShapeDict[currentShapeKey];
                            if (currentShapeValue.Index < modification.Index)
                            {
                                if (modifiedShapeKey != null)
                                {
                                    // Already exists, so we merge the sources
                                    var modifiedShapeValue = modifiedShapeDict[modifiedShapeKey];
                                    modifiedShapeValue.Index |= modification.Index;
                                    if (!modifiedShapeValue.Sources.ContainsSame(currentShapeKey))
                                    {
                                        modifiedShapeValue.Sources.Add(currentShapeKey);
                                    }
                                    modifiedShapeDict[modifiedShapeKey] = modifiedShapeValue;
                                }
                                else
                                {
                                    modifiedShapeDict[modifiedShape] = (currentShapeValue.Index | modification.Index, [currentShapeKey]);
                                }
                            }
                            else
                            {
                                currentShapeValue.Index |= modification.Index;
                                modifiedShapeDict[modifiedShape] = currentShapeValue;
                                modifiedShapeDict.Remove(currentShapeKey);
                            }
                            currentShapeList.Add(modifiedShape);
                            continue;
                        }
                    }

                    // Check if the shape already exists in the modifiedShapeMap
                    if (modifiedShapeKey != null)
                    {
                        // If the shape already exists in the modifiedShapeMap, we update its index and sources
                        var existingValue = modifiedShapeDict[modifiedShapeKey];
                        existingValue.Index |= modification.Index;
                        if (!existingValue.Sources.ContainsSame(currentShape) && !currentShape.IsSame(modifiedShapeKey))
                        {
                            existingValue.Sources.Add(currentShape);
                        }
                        modifiedShapeDict[modifiedShapeKey] = existingValue;
                        continue;
                    }

                    modifiedShapeDict[modifiedShape] = (modification.Index, [currentShape]);
                    currentShapeList.Add(modifiedShape);
                }
            }

            if (modification.Filters != null)
            {
                CreateModifierSubshapeContext context = new()
                {
                    CurrentModification = modification,
                    ShapeDictionary = modifiedShapeDict
                };
                modification.Filters.ForEach(filter => filter(context));
            }
        }

        // Create named shapes for all modified shapes
        foreach (var (modifiedShape, (index, sources)) in modifiedShapeDict)
        {
            addNamedSubshape(name, modifiedShape, index, sources.ToArray());
        }
    }

    //--------------------------------------------------------------------------------------------------

    static List<TopoDS_Shape> _GetModifiedShapes(TopoDS_Shape sourceShape, BRepTools_History history)
    {
        List<TopoDS_Shape> processedShapes = new();
        var modifiedShapes = history.Modified(sourceShape);
        if (modifiedShapes?.Size() > 0)
        {
            processedShapes.AddRange(modifiedShapes);
        }

        var generatedShapes = history.Generated(sourceShape);
        if (generatedShapes?.Size() > 0)
        {
            processedShapes.AddRange(generatedShapes);
        }

        return processedShapes;
    }

    //--------------------------------------------------------------------------------------------------

    #endregion

    #region Make names unique

    static List<TopoDS_Shape> _FindNonDistinctEntries(ShapeNameDictionary shapeDict)
    {
        List<TopoDS_Shape> nonDistinctKeys = new();
        ShapeNameDictionary processedValues = new();

        foreach (var (key, value) in shapeDict)
        {
            // Check if this value list is equivalent to any already processed value
            var shapeType = key.ShapeType();
            var equivalentEntry = processedValues.FirstOrDefault(entry => entry.Key.ShapeType() == shapeType
                                                                          && value.Index == entry.Value.Index
                                                                          && value.Sources.Count == entry.Value.Sources.Count
                                                                          && value.Sources.ContainsAllSame(entry.Value.Sources));

            if (equivalentEntry.Key != null)
            {
                // Found a duplicate value
                nonDistinctKeys.Add(equivalentEntry.Key);
                nonDistinctKeys.Add(key);
            }
            else
            {
                processedValues[key] = value;
            }
        }

        return nonDistinctKeys;
    }

    //--------------------------------------------------------------------------------------------------

    /// <summary>
    /// Enhances non-distinct entries by searching for adjacent faces of the given shape and referencing them as sources.
    /// To find the adjacent face of a given face, split edges are used.
    /// </summary>
    static void _UniquifyByAdjacentFaces(CreateModifierSubshapeContext context)
    {
        var shapeDict = context.ShapeDictionary;
        var modification = context.CurrentModification;

        var resultShape = modification.ResultShape;
        if (resultShape == null)
            return;

        var nonDistinctEntries = _FindNonDistinctEntries(shapeDict);
        if (nonDistinctEntries.Count == 0)
            return;

        foreach (var shape in nonDistinctEntries.Distinct())
        {
            if (!shapeDict.TryGetValue(shape, out var shapeDesc))
                continue;

            TopAbs_ShapeEnum shapeType = shape.ShapeType();
            if (shapeType == TopAbs_ShapeEnum.FACE)
            {
                // Strategy:
                // Enhance non-distinct entries with adjacent face references, using faces with split edges between them.
                if (modification.AuxEdges != null)
                {
                    var face = shape.ToFace();
                    var sectionEdgesOfFace = shape.Edges().Where(modification.AuxEdges.ContainsSame);
                    // A section edge may have no other adjacent face, and an adjacent face which was not
                    // modified has no entry in the dictionary, thus no sources.
                    var adjacantFaces = sectionEdgesOfFace.Select(se => FaceAlgo.FindConnectedFace(modification.ResultShape, face, se))
                                                          .WhereNotNull();
                    var adjacantSources = adjacantFaces.SelectMany(f => shapeDict.FirstSameOrDefault(f).Sources ?? []).WhereNotNull();
                    shapeDesc.Sources.AddRange(adjacantSources.Where(ads => !shapeDesc.Sources.ContainsSame(ads)));
                }
            }
            else if (shapeType == TopAbs_ShapeEnum.EDGE)
            {
                // Strategy:
                // Enhance non-distinct entries with adjacent face references of the given edge.
                var edge = shape.ToEdge();
                (TopoDS_Face face1, TopoDS_Face face2) = EdgeAlgo.FindAdjacentFaces(modification.ResultShape, edge);
                var face1Sources = shapeDict.FirstSameOrDefault(face1);
                if (face1Sources.Sources != null)
                {
                    shapeDesc.Sources.AddRange(face1Sources.Sources.Where(item => !shapeDesc.Sources.ContainsSame(item)));
                }

                var face2Sources = shapeDict.FirstSameOrDefault(face2);
                if (face2Sources.Sources != null)
                {
                    shapeDesc.Sources.AddRange(face2Sources.Sources.Where(item => !shapeDesc.Sources.ContainsSame(item)));
                }
            }
        }
    }

    //--------------------------------------------------------------------------------------------------

    /// <summary>
    /// Enhances edge entries by searching for an adjacent split edge and referencing the adjacent faces of that edge. 
    /// </summary>
    static void _UniquifyByAdjacentSplitEdgeFaces(CreateModifierSubshapeContext context)
    {
        var shapeDict = context.ShapeDictionary;
        var modification = context.CurrentModification;

        var resultShape = modification.ResultShape;
        if (resultShape == null)
            return;
        if (modification.AuxEdges == null)
            return;

        var nonDistinctEntries = _FindNonDistinctEntries(shapeDict);
        if (nonDistinctEntries.Count == 0)
            return;

        foreach (var shape in nonDistinctEntries.Distinct())
        {
            if (!shapeDict.TryGetValue(shape, out var shapeDesc))
                continue;

            TopAbs_ShapeEnum shapeType = shape.ShapeType();
            if (shapeType == TopAbs_ShapeEnum.EDGE)
            {
                // Find section edge and get the adjacent face which leads to splitting
                var edge = shape.ToEdge();
                foreach (var sectionEdge in modification.AuxEdges.Where(se => EdgeAlgo.FindSharedVertex(edge, se) != null))
                {
                    var (face1, face2) = EdgeAlgo.FindAdjacentFaces(modification.ResultShape, sectionEdge);
                    if (face1 != null)
                    {
                        var face1Sources = shapeDict.FirstSameOrDefault(face1);
                        if (face1Sources.Sources != null)
                        {
                            shapeDesc.Sources.AddRange(face1Sources.Sources.Where(item => !shapeDesc.Sources.ContainsSame(item)));
                        }
                    }

                    if (face2 != null)
                    {
                        var face2Sources = shapeDict.FirstSameOrDefault(face2);
                        if (face2Sources.Sources != null)
                        {
                            shapeDesc.Sources.AddRange(face2Sources.Sources.Where(item => !shapeDesc.Sources.ContainsSame(item)));
                        }
                    }
                }
            }
        }
    }

    //--------------------------------------------------------------------------------------------------

    #endregion

    #region Additional filters

    /// <summary>
    /// Find 1:1 relationships of source shape to modified shape. For these shapes the original name is still unique, no new name required.
    /// </summary>
    static void _RemoveBijective(CreateModifierSubshapeContext context)
    {
        
        int modIndex = context.CurrentModification.Index;
        List<TopoDS_Shape> uniqueInputs = context.ShapeDictionary.Where(kvp => kvp.Value.Index == modIndex)
                                                                 .SelectMany(kvp => kvp.Value.Sources.Where(source => kvp.Key.ShapeType() == source.ShapeType()))
                                                                 .GroupBy(source => source)
                                                                 .Where(group => group.Count() == 1)
                                                                 .Select(group => group.Key)
                                                                 .ToList();

        foreach (var (modifiedShape, (index, sources)) in context.ShapeDictionary.ToList())
        {
            if (index == modIndex 
                && sources.Count == 1 
                && uniqueInputs.Contains(sources[0]))
            {
                context.ShapeDictionary.Remove(modifiedShape);
            }
        }
    }

    //--------------------------------------------------------------------------------------------------

    #endregion

}