name: CI

on:
  pull_request:
  push:

permissions:
  checks: write
  
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Restore packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: .\ScriptConsole.cmd restore

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: .\ScriptConsole.cmd build release

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: .\bin\release\

  test:
    name: Run Unit Tests
    needs: build
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: build-artifact
        path: .\bin\release
        
    - name: Run unit tests
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: .\ScriptConsole.cmd test unit
    
    - name: Test Report
      uses: dorny/test-reporter@v2
      if: ${{ !cancelled() }}       # run this step even if previous step failed
      with:
        name: Unit Tests            # Name of the check run which will be created
        path: Test.Unit.xml
        path-replace-backslashes: true
        reporter: dotnet-nunit
        list-suites: failed
        list-tests: failed
        fail-on-error: false
        working-directory: ./bin/release/TestResults
        
        
