name: CI

on: [pull_request, push]
  
permissions:
  checks: write
  
jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - uses: ./.github/actions/build

  test:
    name: Run Unit Tests
    needs: build
    runs-on: windows-latest

    steps:
      - uses: ./.github/actions/test
        
      - uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}
        with:
          name: Unit Tests
          path: Test.Unit.xml
          path-replace-backslashes: true
          reporter: dotnet-nunit
          list-suites: failed
          list-tests: failed
          fail-on-error: true
          working-directory: ./bin/release/TestResults